#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
import actionlib
import japanese_text_to_speech.msg

if __name__ == '__main__':
    rospy.init_node('japanese_tts_test_client')
    action_name = rospy.get_param('~action_name', 'japanese_text_to_speech')
    text = rospy.get_param('~text', 'テスト')

    simple_client = actionlib.SimpleActionClient(action_name, japanese_text_to_speech.msg.SpeakAction)

    rospy.loginfo('Waiting japanese_text_to_speech server')
    simple_client.wait_for_server()

    rospy.loginfo('Sending goal to server')
    goal = japanese_text_to_speech.msg.SpeakGoal()
    goal.text = text
    simple_client.send_goal_and_wait(goal)